/*
 * The Magelan Project - Vector Graphics Library and Editor
 * Copyright (c) 2003-2004, Assen Antov and Larisa Feldman. All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without 
 * modification, are permitted provided that the following conditions are met:
 * 
 * o Redistributions of source code must retain the above copyright notice, 
 *   this list of conditions and the following disclaimer. 
 * 
 * o Redistributions in binary form must reproduce the above copyright notice, 
 *   this list of conditions and the following disclaimer in the documentation 
 *   and/or other materials provided with the distribution. 
 * 
 * o Neither the name Magelan nor the names of project members and
 *   contributors may be used to endorse or promote products derived 
 *   from this software without specific prior written permission. 
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" 
 * AND ANY EXPRESSED OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, 
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR 
 * PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR 
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, 
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, 
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; 
 * OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, 
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR 
 * OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, 
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 * 
 * Suggestions, comments and fixes should be sent to:
 * aantov@users.sourceforge.net
 * larisa@users.sourceforge.net
 */
package org.magelan.editor.ui;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;

import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import javax.swing.JToggleButton;

import org.magelan.commons.Lang;
import org.magelan.commons.ui.Icons;
import org.magelan.core.style.Layer;
import org.magelan.editor.Editor;


/**
 * Generated by V<i>isual</i> Factory 1.0 (c) 2001 by Assen Antov Fri Aug 31
 * 16:58:57 GMT+03:00 2001
 *
 * @author Assen Antov
 * @version 1.0
 */
public class LayerCustomizerLoader extends javax.swing.JPanel {
	
	private static Lang lang = Lang.getLang(Editor.STRINGS);
	
	// variables
	public JPanel namePanel;
	public JLabel component7;
	public JTextField nameField;
	public JPanel accessPanel;
	public JLabel component10;
	public JToggleButton visibleButton;
	public JToggleButton frozenButton;
	public JToggleButton lockedButton;
	public JPanel colorPanel;
	public JLabel component15;
	public JButton colorButton;
	public JPanel lineStylePanel;
	public JLabel component18;
	public LineStyleControl lineStyleCombo;
	public JPanel thicknessPanel;
	public JLabel component21;
	public ThicknessEditor thicknessCombo;

	//~ Constructors -----------------------------------------------------------

	/**

						*/
	public LayerCustomizerLoader() {
		// JFrame
		setName("LayerCustomizer"); //$NON-NLS-1$
		setPreferredSize(new Dimension(320, 550));
		setLayout(new FlowLayout(FlowLayout.CENTER, 5, 0));
		setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(),
												   lang.getString("Layer_Options_2"))); //$NON-NLS-1$

		// JPanel
		namePanel = createPanel("namePanel"); //$NON-NLS-1$
		add(namePanel);

		// JLabel
		component7 = new JLabel();
		component7.setText(lang.getString("Layer_Name__4")); //$NON-NLS-1$
		component7.setName("component7"); //$NON-NLS-1$
		component7.setPreferredSize(new Dimension(80, 17));
		namePanel.add(component7);

		// JTextField
		nameField = new JTextField();
		nameField.setText(""); //$NON-NLS-1$
		nameField.setName("nameField"); //$NON-NLS-1$
		nameField.setPreferredSize(new Dimension(180, 20));
		namePanel.add(nameField);

		// JPanel
		accessPanel = createPanel("accessPanel"); //$NON-NLS-1$
		add(accessPanel);

		// JLabel
		component10 = new JLabel();
		component10.setText(lang.getString("Access__9")); //$NON-NLS-1$
		component10.setName("component10"); //$NON-NLS-1$
		component10.setPreferredSize(new Dimension(80, 17));
		accessPanel.add(component10);

		// JButton
		visibleButton = new JToggleButton();
		visibleButton.setText(""); //$NON-NLS-1$
		visibleButton.setActionCommand("visible"); //$NON-NLS-1$
		visibleButton.setIcon(Icons.VISIBLE_ICON);
		visibleButton.setName("visibleButton"); //$NON-NLS-1$
		visibleButton.setPreferredSize(new Dimension(20, 20));
		visibleButton.setContentAreaFilled(false);
		accessPanel.add(visibleButton);

		// JButton
		frozenButton = new JToggleButton();
		frozenButton.setText(""); //$NON-NLS-1$
		frozenButton.setActionCommand("frozen"); //$NON-NLS-1$
		frozenButton.setIcon(Icons.FROZEN_ICON);
		frozenButton.setName("frozenButton"); //$NON-NLS-1$
		frozenButton.setPreferredSize(new Dimension(20, 20));
		frozenButton.setContentAreaFilled(false);
		accessPanel.add(frozenButton);

		// JButton
		lockedButton = new JToggleButton();
		lockedButton.setText(""); //$NON-NLS-1$
		lockedButton.setActionCommand("locked"); //$NON-NLS-1$
		lockedButton.setIcon(Icons.LOCKED_ICON);
		lockedButton.setName("lockedButton"); //$NON-NLS-1$
		lockedButton.setPreferredSize(new Dimension(20, 20));
		lockedButton.setContentAreaFilled(false);
		accessPanel.add(lockedButton);

		// JPanel
		colorPanel = createPanel("colorPanel"); //$NON-NLS-1$
		add(colorPanel);

		// JLabel
		component15 = new JLabel();
		component15.setText(lang.getString("Color__24")); //$NON-NLS-1$
		component15.setName("component15"); //$NON-NLS-1$
		component15.setPreferredSize(new Dimension(80, 17));
		colorPanel.add(component15);

		// JButton
		colorButton = new JButton();
		colorButton.setText(""); //$NON-NLS-1$
		colorButton.setActionCommand("colorButton"); //$NON-NLS-1$
		colorButton.setName("colorButton"); //$NON-NLS-1$
		colorButton.setPreferredSize(new Dimension(70, 20));
		colorPanel.add(colorButton);

		// JPanel
		lineStylePanel = createPanel("lineStylePanel"); //$NON-NLS-1$
		add(lineStylePanel);

		// JLabel
		component18 = new JLabel();
		component18.setText(lang.getString("Line_Style__30")); //$NON-NLS-1$
		component18.setName("component18"); //$NON-NLS-1$
		component18.setPreferredSize(new Dimension(80, 17));
		lineStylePanel.add(component18);

		// JComboBox
		lineStyleCombo = new LineStyleControl();

		//lineStyleCombo.setActionCommand("comboBoxChanged");
		//lineStyleCombo.setEditable(false);
		//lineStyleCombo.setMaximumRowCount(8);
		lineStyleCombo.setName("lineStyleCombo"); //$NON-NLS-1$
		lineStyleCombo.setPreferredSize(new Dimension(180, 20));
		lineStylePanel.add(lineStyleCombo);

		// JPanel
		thicknessPanel = createPanel("thicknessPanel"); //$NON-NLS-1$
		add(thicknessPanel);

		// JLabel
		component21 = new JLabel();
		component21.setText(lang.getString("Thickness__34")); //$NON-NLS-1$
		component21.setName("component21"); //$NON-NLS-1$
		component21.setToolTipText(""); //$NON-NLS-1$
		component21.setPreferredSize(new Dimension(80, 17));
		thicknessPanel.add(component21);

		// JComboBox
		thicknessCombo = new ThicknessEditor();
		thicknessCombo.setActionCommand("comboBoxChanged"); //$NON-NLS-1$
		thicknessCombo.setEditable(false);
		thicknessCombo.setMaximumRowCount(8);
		thicknessCombo.setName("thicknessCombo"); //$NON-NLS-1$
		thicknessCombo.setPreferredSize(new Dimension(180, 20));
		thicknessPanel.add(thicknessCombo);

		java.util.Vector layers = new java.util.Vector();

		Layer l0 = new Layer(lang.getString("0_39")); //$NON-NLS-1$
		l0.setColor(Color.red);
		l0.setVisible(false);
		layers.add(l0);

		Layer l1 = new Layer(lang.getString("Default_40")); //$NON-NLS-1$
		l1.setColor(Color.blue);
		l1.setVisible(false);
		layers.add(l1);

		LayerEditor ed = new LayerEditor(layers);
		ed.setBackground(Color.white);
		ed.setPreferredSize(new Dimension(130, 80));
		add(new JScrollPane(ed));

		//	ed.setPopupVisible(true);
		add(new LayerVisibleEditor(l0));
		add(new LayerVisibleEditor(l0));

		//		JList lst = new JList(layers);
		//		lst.setPreferredSize(new Dimension(130, 50));
		//		lst.setListCellRenderer(new LayerEditor.CellRenderer());
		//		add(lst);

		/*
		                ModelNetwork net = new ModelNetwork();

		                Layer lr1 = new Layer("Map");
		                lr1.setColor(Color.red);
		                lr1.setVisible(false);
		                lr1.setAlpha(0.3f);
		                //lr1.setCompositeRule(AlphaComposite.CLEAR);
		                net.addLayer(lr1);

		                Layer lr2 = new Layer("Rivers");
		                lr2.setColor(Color.blue);
		                lr2.setVisible(false);
		                lr2.setAlpha(0.7f);
		        //        lr2.setCompositeRule(AlphaComposite.XOR);
		                net.addLayer(lr2);

		                Layer lr3 = new Layer("Lakes");
		                lr3.setColor(new Color(100, 100, 255));
		                lr3.setVisible(false);
		                lr3.setAlpha(0.1f);
		        //        lr3.setCompositeRule(AlphaComposite.SRC_OUT);
		                net.addLayer(lr3);

		                Layer lr4 = new Layer("Forests");
		                lr4.setColor(new Color(200, 255, 200));
		                lr4.setFrozen(true);
		                lr4.setAlpha(0.65f);
		        //        lr3.setCompositeRule(AlphaComposite.SRC_OUT);
		                net.addLayer(lr4);

		                LayerComboBox lc = new LayerComboBox(net);
		                lc.setPreferredSize(new Dimension(250, 25));
		                add(lc);

		                add(new AlphaCompositeView(lr4));

		                add(new AlphaCompositeControl(lr4));
		                */
	}

	//~ Methods ----------------------------------------------------------------

	/**
	 * Creates an option panel.
	 *
	 * @param name
	 *
	 * @return
	 */
	public JPanel createPanel(String name) {
		JPanel panel = new JPanel();
		panel.setName(name);
		panel.setPreferredSize(new Dimension(300, 27));
		panel.setLayout(new FlowLayout(FlowLayout.LEFT));

		return panel;
	}
}