/*
 * The Magelan Project - Vector Graphics Library and Editor
 * Copyright (c) 2003-2004, Assen Antov and Larisa Feldman. All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without 
 * modification, are permitted provided that the following conditions are met:
 * 
 * o Redistributions of source code must retain the above copyright notice, 
 *   this list of conditions and the following disclaimer. 
 * 
 * o Redistributions in binary form must reproduce the above copyright notice, 
 *   this list of conditions and the following disclaimer in the documentation 
 *   and/or other materials provided with the distribution. 
 * 
 * o Neither the name Magelan nor the names of project members and
 *   contributors may be used to endorse or promote products derived 
 *   from this software without specific prior written permission. 
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" 
 * AND ANY EXPRESSED OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, 
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR 
 * PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR 
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, 
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, 
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; 
 * OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, 
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR 
 * OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, 
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 * 
 * Suggestions, comments and fixes should be sent to:
 * aantov@users.sourceforge.net
 * larisa@users.sourceforge.net
 */
package org.magelan.editor.extension;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Insets;

import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

import org.magelan.commons.Lang;
import org.magelan.commons.ui.Icons;
import org.magelan.editor.Editor;


/**
 * This class is a part of V<i>sual</i> Factory GUI
 * 
 * <p>
 * Generated by V<i>isual</i> Factory 1.0 (c) 2001 by Assen Antov Sat Mar 16
 * 17:20:02 EET 2002
 * </p>
 *
 * @author Assen Antov
 * @version 1.0
 */
public class LineStyleManagerLoader extends JDialog {

	private static Lang lang = Lang.getLang(Editor.STRINGS);

	// variables
	public JPanel component5;
	public JPanel panel1;
	public JScrollPane scroll;
	public JPanel panel2;
	public JButton setButton;
	public JButton removeButton;
	public JPanel component13;
	public JButton helpButton;
	public JButton okButton;


	/**
	 */
	public LineStyleManagerLoader() {
		// JDialog
		setName("LineStyleManager"); //$NON-NLS-1$
		setBounds(230, 125, 475, 280);
		setTitle(lang.getString("LineStyleManager.title")); //$NON-NLS-1$
		setResizable(true);
		setModal(true);
		getContentPane().setLayout(new FlowLayout());
		setDefaultCloseOperation(1);

		getContentPane().setLayout(new BorderLayout());

		// JPanel
		panel1 = new JPanel();
		panel1.setName("panel1"); //$NON-NLS-1$
		panel1.setPreferredSize(new Dimension(455, 210));
		getContentPane().add(panel1, BorderLayout.CENTER);

		panel1.setLayout(new BorderLayout());

		// JScrollPane
		scroll = new JScrollPane();
		scroll.setName("scroll"); //$NON-NLS-1$
		scroll.setPreferredSize(new Dimension(340, 170));
		panel1.add(scroll, BorderLayout.CENTER);

		// JPanel
		panel2 = new JPanel();
		panel2.setName("panel2"); //$NON-NLS-1$
		panel2.setPreferredSize(new Dimension(90, 170));
		panel1.add(panel2, BorderLayout.EAST);

		// JButton
		setButton = new JButton();
		setButton.setText(lang.getString("LineStyleManager.button.current")); //$NON-NLS-1$
		setButton.setActionCommand("Set"); //$NON-NLS-1$
		setButton.setName("setButton"); //$NON-NLS-1$
		setButton.setPreferredSize(new Dimension(82, 26));
		panel2.add(setButton);

		// VFRemoveButton
		removeButton = new JButton();
		removeButton.setText(lang.getString("LineStyleManager.button.remove")); //$NON-NLS-1$
		removeButton.setActionCommand("Remove"); //$NON-NLS-1$
		removeButton.setMargin(new Insets(2, 4, 2, 6));
		removeButton.setIcon(Icons.ERASE_ICON);
		removeButton.setName("removeButton"); //$NON-NLS-1$
		removeButton.setPreferredSize(new Dimension(82, 26));
		panel2.add(removeButton);

		// JPanel
		component13 = new JPanel();
		component13.setName("component13"); //$NON-NLS-1$
		component13.setPreferredSize(new Dimension(59, 10));
		panel2.add(component13);

		JPanel panel3 = new JPanel();
		getContentPane().add(panel3, BorderLayout.SOUTH);

		// VFOKButton
		okButton = new JButton();
		okButton.setText(lang.getString("common.ok")); //$NON-NLS-1$
		okButton.setActionCommand("OK"); //$NON-NLS-1$
		okButton.setMargin(new Insets(2, 10, 2, 14));
		okButton.setIcon(Icons.OK_ICON);
		okButton.setName("okButton"); //$NON-NLS-1$
		okButton.setPreferredSize(new Dimension(82, 26));
		panel3.add(okButton);

		// VFHelpButton
		helpButton = new JButton();
		helpButton.setText(lang.getString("common.help")); //$NON-NLS-1$
		helpButton.setActionCommand("Help"); //$NON-NLS-1$
		helpButton.setIcon(Icons.HELP_ICON);
		helpButton.setName("helpButton"); //$NON-NLS-1$
		helpButton.setPreferredSize(new Dimension(82, 26));
		panel3.add(helpButton);
	}
}